name: build

on:
  workflow_call:
  push:
    branches: [ "dev", "development" ]

jobs:
  run_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build