name: release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  run_tests:
    uses: mrdcvlsc/scheduling-system-frontend/.github/workflows/tests.yml@main

  run_build:
    uses: mrdcvlsc/scheduling-system-frontend/.github/workflows/build.yml@main

  build:
    runs-on: ubuntu-latest

    needs: 
    - run_tests
    - run_build

    steps:

    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm install

    - name: Set js fetch scripts to production mode
      run: | 
        sed -i 's/const DEV = true/const DEV = false/' src/js/basics.js
        sed -i 's/}, 1357)/}, 60000)' src/schedule/class_schedule.jsx

    - name: Run Build
      run: npm run build

    - name: Zip Build
      run: zip -r dist.zip dist
      
    - name: Create Github Release
      run: gh release create build-v${{ github.run_number }} dist.zip --title "Release scheduling system frontend build version ${{ github.run_number }}" --notes "Build Number ${{ github.run_number }}" --draft=false --prerelease=false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}